Make staticcheck happy
```
$ staticcheck
apihandler.go:434:4: error strings should not be capitalized (ST1005)
dnshandler.go:49:6: func xxxGetKeepFunc is unused (U1000)
dnshandler.go:101:12: unnecessary assignment to the blank identifier (S1005)
dnshandler.go:267:3: redundant return statement (S1023)
dnshandler.go:378:3: redundant return statement (S1023)
main.go:26:2: var soreuseport is unused (U1000)
main.go:76:3: printf-style function with dynamic format string and no further arguments should use print-style function instead (SA1006)
output.go:115:11: unnecessary assignment to the blank identifier (S1005)
output.go:116:5: empty branch (SA9003)
output.go:172:12: unnecessary assignment to the blank identifier (S1005)
output.go:215:18: this result of append is never used, except maybe in other appends (SA4010)
output.go:409:12: empty branch (SA9003)
refreshengine.go:58:14: should use time.Until instead of t.Sub(time.Now()) (S1024)
refreshengine.go:64:3: should use for range instead of for { select {} } (S1000)
sources.go:284:8: should omit comparison to bool constant, can be simplified to !s["active"].(bool) (S1002)
sources.go:466:10: error strings should not be capitalized (ST1005)
sources.go:466:10: error strings should not end with punctuation or newlines (ST1005)
version.go:4:7: const appDate is unused (U1000)
version.go:5:7: const appName is unused (U1000)
xfr.go:153:11: assigning the result of this type assertion to a variable (switch rr := rr.(type)) could eliminate type assertions in switch cases (S1034)
	xfr.go:155:17: could eliminate this type assertion
```